name: 'Deploy to S3'
description: 'Deploy a static website to S3'
inputs:
    bucket:
        description: 'The name of the S3 bucket to deploy to'
        required: true
    bucket-region:
        description: 'The AWS region where the S3 bucket is located'
        required: true
    dist-folder:
        description: 'The path to the folder containing the static website files to deploy'
        required: true
outputs:
   website-url:
       description: 'The URL of the deployed website'
runs:
    using: 'node20'
    main: 'main.js'
    
